// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: battlefield.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RadarService_StreamRadar_FullMethodName = "/battlefield.RadarService/StreamRadar"
)

// RadarServiceClient is the client API for RadarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RadarService: gRPC service cho real-time radar streaming
type RadarServiceClient interface {
	// StreamRadar: server-streaming RPC, push RadarSnapshot mỗi 100ms
	StreamRadar(ctx context.Context, in *StreamRadarRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RadarSnapshot], error)
}

type radarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRadarServiceClient(cc grpc.ClientConnInterface) RadarServiceClient {
	return &radarServiceClient{cc}
}

func (c *radarServiceClient) StreamRadar(ctx context.Context, in *StreamRadarRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RadarSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RadarService_ServiceDesc.Streams[0], RadarService_StreamRadar_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRadarRequest, RadarSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadarService_StreamRadarClient = grpc.ServerStreamingClient[RadarSnapshot]

// RadarServiceServer is the server API for RadarService service.
// All implementations must embed UnimplementedRadarServiceServer
// for forward compatibility.
//
// RadarService: gRPC service cho real-time radar streaming
type RadarServiceServer interface {
	// StreamRadar: server-streaming RPC, push RadarSnapshot mỗi 100ms
	StreamRadar(*StreamRadarRequest, grpc.ServerStreamingServer[RadarSnapshot]) error
	mustEmbedUnimplementedRadarServiceServer()
}

// UnimplementedRadarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRadarServiceServer struct{}

func (UnimplementedRadarServiceServer) StreamRadar(*StreamRadarRequest, grpc.ServerStreamingServer[RadarSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamRadar not implemented")
}
func (UnimplementedRadarServiceServer) mustEmbedUnimplementedRadarServiceServer() {}
func (UnimplementedRadarServiceServer) testEmbeddedByValue()                      {}

// UnsafeRadarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RadarServiceServer will
// result in compilation errors.
type UnsafeRadarServiceServer interface {
	mustEmbedUnimplementedRadarServiceServer()
}

func RegisterRadarServiceServer(s grpc.ServiceRegistrar, srv RadarServiceServer) {
	// If the following call panics, it indicates UnimplementedRadarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RadarService_ServiceDesc, srv)
}

func _RadarService_StreamRadar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRadarRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RadarServiceServer).StreamRadar(m, &grpc.GenericServerStream[StreamRadarRequest, RadarSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RadarService_StreamRadarServer = grpc.ServerStreamingServer[RadarSnapshot]

// RadarService_ServiceDesc is the grpc.ServiceDesc for RadarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RadarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battlefield.RadarService",
	HandlerType: (*RadarServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRadar",
			Handler:       _RadarService_StreamRadar_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "battlefield.proto",
}
