// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: battlefield.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJECT_TYPE_UNSPECIFIED ObjectType = 0
	ObjectType_UAV                     ObjectType = 1
	ObjectType_MISSILE                 ObjectType = 2
	ObjectType_THREAT                  ObjectType = 3
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIED",
		1: "UAV",
		2: "MISSILE",
		3: "THREAT",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIED": 0,
		"UAV":                     1,
		"MISSILE":                 2,
		"THREAT":                  3,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_battlefield_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_battlefield_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{0}
}

type ThreatLevel int32

const (
	ThreatLevel_THREAT_LEVEL_UNSPECIFIED ThreatLevel = 0
	ThreatLevel_LOW                      ThreatLevel = 1
	ThreatLevel_MEDIUM                   ThreatLevel = 2
	ThreatLevel_HIGH                     ThreatLevel = 3
	ThreatLevel_CRITICAL                 ThreatLevel = 4
)

// Enum value maps for ThreatLevel.
var (
	ThreatLevel_name = map[int32]string{
		0: "THREAT_LEVEL_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	ThreatLevel_value = map[string]int32{
		"THREAT_LEVEL_UNSPECIFIED": 0,
		"LOW":                      1,
		"MEDIUM":                   2,
		"HIGH":                     3,
		"CRITICAL":                 4,
	}
)

func (x ThreatLevel) Enum() *ThreatLevel {
	p := new(ThreatLevel)
	*p = x
	return p
}

func (x ThreatLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_battlefield_proto_enumTypes[1].Descriptor()
}

func (ThreatLevel) Type() protoreflect.EnumType {
	return &file_battlefield_proto_enumTypes[1]
}

func (x ThreatLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatLevel.Descriptor instead.
func (ThreatLevel) EnumDescriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{1}
}

// Layer phân biệt nguồn gốc đối tượng
type Layer int32

const (
	Layer_LAYER_UNSPECIFIED Layer = 0
	Layer_CIVIL             Layer = 1
	Layer_MILITARY          Layer = 2
)

// Enum value maps for Layer.
var (
	Layer_name = map[int32]string{
		0: "LAYER_UNSPECIFIED",
		1: "CIVIL",
		2: "MILITARY",
	}
	Layer_value = map[string]int32{
		"LAYER_UNSPECIFIED": 0,
		"CIVIL":             1,
		"MILITARY":          2,
	}
)

func (x Layer) Enum() *Layer {
	p := new(Layer)
	*p = x
	return p
}

func (x Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_battlefield_proto_enumTypes[2].Descriptor()
}

func (Layer) Type() protoreflect.EnumType {
	return &file_battlefield_proto_enumTypes[2]
}

func (x Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer.Descriptor instead.
func (Layer) EnumDescriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{2}
}

// FlightEvent: dữ liệu máy bay dân sự từ OpenSky Network
type FlightEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Icao24        string                 `protobuf:"bytes,1,opt,name=icao24,proto3" json:"icao24,omitempty"`
	Callsign      string                 `protobuf:"bytes,2,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,5,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed         float64                `protobuf:"fixed64,6,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,7,opt,name=heading,proto3" json:"heading,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightEvent) Reset() {
	*x = FlightEvent{}
	mi := &file_battlefield_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightEvent) ProtoMessage() {}

func (x *FlightEvent) ProtoReflect() protoreflect.Message {
	mi := &file_battlefield_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightEvent.ProtoReflect.Descriptor instead.
func (*FlightEvent) Descriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{0}
}

func (x *FlightEvent) GetIcao24() string {
	if x != nil {
		return x.Icao24
	}
	return ""
}

func (x *FlightEvent) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *FlightEvent) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FlightEvent) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *FlightEvent) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *FlightEvent) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *FlightEvent) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *FlightEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// MilitaryEvent: dữ liệu đối tượng quân sự giả lập
type MilitaryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ObjectType             `protobuf:"varint,2,opt,name=type,proto3,enum=battlefield.ObjectType" json:"type,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,5,opt,name=alt,proto3" json:"alt,omitempty"`
	Heading       float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	Speed         float64                `protobuf:"fixed64,7,opt,name=speed,proto3" json:"speed,omitempty"`
	ThreatLevel   ThreatLevel            `protobuf:"varint,8,opt,name=threat_level,json=threatLevel,proto3,enum=battlefield.ThreatLevel" json:"threat_level,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MilitaryEvent) Reset() {
	*x = MilitaryEvent{}
	mi := &file_battlefield_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MilitaryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MilitaryEvent) ProtoMessage() {}

func (x *MilitaryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_battlefield_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MilitaryEvent.ProtoReflect.Descriptor instead.
func (*MilitaryEvent) Descriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{1}
}

func (x *MilitaryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MilitaryEvent) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *MilitaryEvent) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *MilitaryEvent) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *MilitaryEvent) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *MilitaryEvent) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *MilitaryEvent) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *MilitaryEvent) GetThreatLevel() ThreatLevel {
	if x != nil {
		return x.ThreatLevel
	}
	return ThreatLevel_THREAT_LEVEL_UNSPECIFIED
}

func (x *MilitaryEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MilitaryEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// RadarObject: representation thống nhất mọi đối tượng trên radar
type RadarObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ObjectType             `protobuf:"varint,2,opt,name=type,proto3,enum=battlefield.ObjectType" json:"type,omitempty"`
	Layer         Layer                  `protobuf:"varint,3,opt,name=layer,proto3,enum=battlefield.Layer" json:"layer,omitempty"`
	Callsign      string                 `protobuf:"bytes,4,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Lat           float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,6,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,7,opt,name=alt,proto3" json:"alt,omitempty"`
	Speed         float64                `protobuf:"fixed64,8,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,9,opt,name=heading,proto3" json:"heading,omitempty"`
	ThreatLevel   ThreatLevel            `protobuf:"varint,10,opt,name=threat_level,json=threatLevel,proto3,enum=battlefield.ThreatLevel" json:"threat_level,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarObject) Reset() {
	*x = RadarObject{}
	mi := &file_battlefield_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarObject) ProtoMessage() {}

func (x *RadarObject) ProtoReflect() protoreflect.Message {
	mi := &file_battlefield_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarObject.ProtoReflect.Descriptor instead.
func (*RadarObject) Descriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{2}
}

func (x *RadarObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RadarObject) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *RadarObject) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *RadarObject) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *RadarObject) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RadarObject) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RadarObject) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *RadarObject) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *RadarObject) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *RadarObject) GetThreatLevel() ThreatLevel {
	if x != nil {
		return x.ThreatLevel
	}
	return ThreatLevel_THREAT_LEVEL_UNSPECIFIED
}

func (x *RadarObject) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RadarObject) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// SnapshotStats: thống kê tổng hợp
type SnapshotStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalObjects    int32                  `protobuf:"varint,1,opt,name=total_objects,json=totalObjects,proto3" json:"total_objects,omitempty"`
	CivilAircraft   int32                  `protobuf:"varint,2,opt,name=civil_aircraft,json=civilAircraft,proto3" json:"civil_aircraft,omitempty"`
	UavCount        int32                  `protobuf:"varint,3,opt,name=uav_count,json=uavCount,proto3" json:"uav_count,omitempty"`
	MissileCount    int32                  `protobuf:"varint,4,opt,name=missile_count,json=missileCount,proto3" json:"missile_count,omitempty"`
	ThreatCount     int32                  `protobuf:"varint,5,opt,name=threat_count,json=threatCount,proto3" json:"threat_count,omitempty"`
	CriticalThreats int32                  `protobuf:"varint,6,opt,name=critical_threats,json=criticalThreats,proto3" json:"critical_threats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotStats) Reset() {
	*x = SnapshotStats{}
	mi := &file_battlefield_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotStats) ProtoMessage() {}

func (x *SnapshotStats) ProtoReflect() protoreflect.Message {
	mi := &file_battlefield_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotStats.ProtoReflect.Descriptor instead.
func (*SnapshotStats) Descriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotStats) GetTotalObjects() int32 {
	if x != nil {
		return x.TotalObjects
	}
	return 0
}

func (x *SnapshotStats) GetCivilAircraft() int32 {
	if x != nil {
		return x.CivilAircraft
	}
	return 0
}

func (x *SnapshotStats) GetUavCount() int32 {
	if x != nil {
		return x.UavCount
	}
	return 0
}

func (x *SnapshotStats) GetMissileCount() int32 {
	if x != nil {
		return x.MissileCount
	}
	return 0
}

func (x *SnapshotStats) GetThreatCount() int32 {
	if x != nil {
		return x.ThreatCount
	}
	return 0
}

func (x *SnapshotStats) GetCriticalThreats() int32 {
	if x != nil {
		return x.CriticalThreats
	}
	return 0
}

// RadarSnapshot: payload gửi về client mỗi 100ms
type RadarSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=snapshot_at,json=snapshotAt,proto3" json:"snapshot_at,omitempty"`
	Objects       []*RadarObject         `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	Stats         *SnapshotStats         `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarSnapshot) Reset() {
	*x = RadarSnapshot{}
	mi := &file_battlefield_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarSnapshot) ProtoMessage() {}

func (x *RadarSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_battlefield_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarSnapshot.ProtoReflect.Descriptor instead.
func (*RadarSnapshot) Descriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{4}
}

func (x *RadarSnapshot) GetSnapshotAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotAt
	}
	return nil
}

func (x *RadarSnapshot) GetObjects() []*RadarObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *RadarSnapshot) GetStats() *SnapshotStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// StreamRadarRequest: request từ client (hiện tại trống, có thể thêm filter sau)
type StreamRadarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRadarRequest) Reset() {
	*x = StreamRadarRequest{}
	mi := &file_battlefield_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRadarRequest) ProtoMessage() {}

func (x *StreamRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battlefield_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRadarRequest.ProtoReflect.Descriptor instead.
func (*StreamRadarRequest) Descriptor() ([]byte, []int) {
	return file_battlefield_proto_rawDescGZIP(), []int{5}
}

var File_battlefield_proto protoreflect.FileDescriptor

const file_battlefield_proto_rawDesc = "" +
	"\n" +
	"\x11battlefield.proto\x12\vbattlefield\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\vFlightEvent\x12\x16\n" +
	"\x06icao24\x18\x01 \x01(\tR\x06icao24\x12\x1a\n" +
	"\bcallsign\x18\x02 \x01(\tR\bcallsign\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x05 \x01(\x01R\x03alt\x12\x14\n" +
	"\x05speed\x18\x06 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\a \x01(\x01R\aheading\x12*\n" +
	"\x02ts\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\xb3\x02\n" +
	"\rMilitaryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.battlefield.ObjectTypeR\x04type\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x05 \x01(\x01R\x03alt\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\a \x01(\x01R\x05speed\x12;\n" +
	"\fthreat_level\x18\b \x01(\x0e2\x18.battlefield.ThreatLevelR\vthreatLevel\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12*\n" +
	"\x02ts\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\x8a\x03\n" +
	"\vRadarObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.battlefield.ObjectTypeR\x04type\x12(\n" +
	"\x05layer\x18\x03 \x01(\x0e2\x12.battlefield.LayerR\x05layer\x12\x1a\n" +
	"\bcallsign\x18\x04 \x01(\tR\bcallsign\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x06 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\a \x01(\x01R\x03alt\x12\x14\n" +
	"\x05speed\x18\b \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\t \x01(\x01R\aheading\x12;\n" +
	"\fthreat_level\x18\n" +
	" \x01(\x0e2\x18.battlefield.ThreatLevelR\vthreatLevel\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12=\n" +
	"\flast_updated\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xeb\x01\n" +
	"\rSnapshotStats\x12#\n" +
	"\rtotal_objects\x18\x01 \x01(\x05R\ftotalObjects\x12%\n" +
	"\x0ecivil_aircraft\x18\x02 \x01(\x05R\rcivilAircraft\x12\x1b\n" +
	"\tuav_count\x18\x03 \x01(\x05R\buavCount\x12#\n" +
	"\rmissile_count\x18\x04 \x01(\x05R\fmissileCount\x12!\n" +
	"\fthreat_count\x18\x05 \x01(\x05R\vthreatCount\x12)\n" +
	"\x10critical_threats\x18\x06 \x01(\x05R\x0fcriticalThreats\"\xb2\x01\n" +
	"\rRadarSnapshot\x12;\n" +
	"\vsnapshot_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"snapshotAt\x122\n" +
	"\aobjects\x18\x02 \x03(\v2\x18.battlefield.RadarObjectR\aobjects\x120\n" +
	"\x05stats\x18\x03 \x01(\v2\x1a.battlefield.SnapshotStatsR\x05stats\"\x14\n" +
	"\x12StreamRadarRequest*K\n" +
	"\n" +
	"ObjectType\x12\x1b\n" +
	"\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03UAV\x10\x01\x12\v\n" +
	"\aMISSILE\x10\x02\x12\n" +
	"\n" +
	"\x06THREAT\x10\x03*X\n" +
	"\vThreatLevel\x12\x1c\n" +
	"\x18THREAT_LEVEL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04*7\n" +
	"\x05Layer\x12\x15\n" +
	"\x11LAYER_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05CIVIL\x10\x01\x12\f\n" +
	"\bMILITARY\x10\x022\\\n" +
	"\fRadarService\x12L\n" +
	"\vStreamRadar\x12\x1f.battlefield.StreamRadarRequest\x1a\x1a.battlefield.RadarSnapshot0\x01B\x13Z\x11battlefield/protob\x06proto3"

var (
	file_battlefield_proto_rawDescOnce sync.Once
	file_battlefield_proto_rawDescData []byte
)

func file_battlefield_proto_rawDescGZIP() []byte {
	file_battlefield_proto_rawDescOnce.Do(func() {
		file_battlefield_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battlefield_proto_rawDesc), len(file_battlefield_proto_rawDesc)))
	})
	return file_battlefield_proto_rawDescData
}

var file_battlefield_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_battlefield_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_battlefield_proto_goTypes = []any{
	(ObjectType)(0),               // 0: battlefield.ObjectType
	(ThreatLevel)(0),              // 1: battlefield.ThreatLevel
	(Layer)(0),                    // 2: battlefield.Layer
	(*FlightEvent)(nil),           // 3: battlefield.FlightEvent
	(*MilitaryEvent)(nil),         // 4: battlefield.MilitaryEvent
	(*RadarObject)(nil),           // 5: battlefield.RadarObject
	(*SnapshotStats)(nil),         // 6: battlefield.SnapshotStats
	(*RadarSnapshot)(nil),         // 7: battlefield.RadarSnapshot
	(*StreamRadarRequest)(nil),    // 8: battlefield.StreamRadarRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_battlefield_proto_depIdxs = []int32{
	9,  // 0: battlefield.FlightEvent.ts:type_name -> google.protobuf.Timestamp
	0,  // 1: battlefield.MilitaryEvent.type:type_name -> battlefield.ObjectType
	1,  // 2: battlefield.MilitaryEvent.threat_level:type_name -> battlefield.ThreatLevel
	9,  // 3: battlefield.MilitaryEvent.ts:type_name -> google.protobuf.Timestamp
	0,  // 4: battlefield.RadarObject.type:type_name -> battlefield.ObjectType
	2,  // 5: battlefield.RadarObject.layer:type_name -> battlefield.Layer
	1,  // 6: battlefield.RadarObject.threat_level:type_name -> battlefield.ThreatLevel
	9,  // 7: battlefield.RadarObject.last_updated:type_name -> google.protobuf.Timestamp
	9,  // 8: battlefield.RadarSnapshot.snapshot_at:type_name -> google.protobuf.Timestamp
	5,  // 9: battlefield.RadarSnapshot.objects:type_name -> battlefield.RadarObject
	6,  // 10: battlefield.RadarSnapshot.stats:type_name -> battlefield.SnapshotStats
	8,  // 11: battlefield.RadarService.StreamRadar:input_type -> battlefield.StreamRadarRequest
	7,  // 12: battlefield.RadarService.StreamRadar:output_type -> battlefield.RadarSnapshot
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_battlefield_proto_init() }
func file_battlefield_proto_init() {
	if File_battlefield_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battlefield_proto_rawDesc), len(file_battlefield_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_battlefield_proto_goTypes,
		DependencyIndexes: file_battlefield_proto_depIdxs,
		EnumInfos:         file_battlefield_proto_enumTypes,
		MessageInfos:      file_battlefield_proto_msgTypes,
	}.Build()
	File_battlefield_proto = out.File
	file_battlefield_proto_goTypes = nil
	file_battlefield_proto_depIdxs = nil
}
